### ISSUE TITLE
Add bitness of Dart VM

### ISSUE THREAD

**Issue by martinsik** [mezoni/system_info#2]
I think it would be useful to be able to get built architecture of current Dart's VM. My usecase is compiling native extensions with https://github.com/mezoni/ccompile.

The problem is that native extensions have to be compiled for the same arhitecture as the Dart VM importing them. For example I'm running OS X 10.10 on 2,5 GHz Intel Core i5 which is x86_64 processor, but Dart VM is compiled for i386 (32bit) architecture. 
```
print(Platform.version)

Dart VM version: 1.10.1 (Mon May 11 11:02:10 2015) on "macos_ia32"
```
Therefore all native extension that I want to use have be compiled as i386 (32bit) binaries.

**Comment by mezoni** [comment]
Dart VM executed in a some "user space".
CPU type, kernel bitness and user space (aka program bitness) is a different things.
If you run a 32-bit program (Dart VM macos_ia32) then you run it in the following environment:

1. CPU type - phisical (virtual) CPU
2. Kernel type - depends on system features
3. User space - space for bitness of program

This is a features of package "system info".

That is, `SysInfo.userSpaceBitness` give you a 'Dart VM bitness'.

According to the package `ccompile`.
Package "compile" (as is) uses a static configuration from a some file (eg. conf.yaml).
It suitable for compiling the native extension for current "user space" or for specified in this config file.

sample_extension.yaml

```yaml
bits: 0 # 0 means the bits of Dart SDK
```

If this is acceptable to you to change field `bits` in config then you can re-configure it in such way.

```yaml
bits: 64
```

Another way is to change this value dynamically:

```
var project = builder.loadProject(projectPath);
// Change bitness here for you requirements
project.bits = MY_OWN_BITS;
var result = builder.buildAndClean(project, workingDirectory);
```

**Comment by mezoni** [comment]
>> Package "compile" (as is) uses a static configuration from a some file (eg. conf.yaml).

This statement is not quite correct.
It only correct if you use `ccompile` directly as the command line tool.
In all other cases you can specifiy configuration in three ways:

1. Built-in in package "ccompile" (in json or yaml format) (eg. [sample_extension.yaml](https://github.com/mezoni/ccompile/blob/master/example/sample_extension.yaml))
2. Create instance of class `Procject` directly in your code.
3. Use your own format and convert it into instance described in the paragraph 2

**Comment by martinsik** [comment]
`SysInfo.userSpaceBitness` returns `64` on my platform and it comes from running:
```$ getconf LONG_BIT```

This has nothing to do with how Dart VM was compiled and if I wanted to use it in `ccompile` it will compile a binary for 64 architecure which can't be imported from `macos_ia32` Dart VM.

Setting `project.bits` doesn't solve the problem because then everyone would have to change it specifically for their platform.

```
$ dart bin/system_info.dart 
Kernel architecture     : x86_64
Kernel bitness          : 64
Kernel name             : Darwin
Kernel version          : 14.3.0
Operating system name   : Mac OS X
Operating system version: 10.10.3
User directory          : /Users/martin
User id                 : 501
User name               : martin
User space bitness      : 64
Number of processors    : 2
  Architecture          : X86_64
  Name                  : Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Socket                : 0
  Vendor                : GenuineIntel
  Architecture          : X86_64
  Name                  : Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Socket                : 0
  Vendor                : GenuineIntel
Total physical memory   : 33554432 MB
Free physical memory    : 3089 MB
Total virtual memory    : 7413 MB
Free virtual memory     : 3088 MB
Virtual memory size     : 650 MB
```

**Comment by mezoni** [comment]
>> SysInfo.userSpaceBitness returns 64 on my platform and it comes from running:
>> $ getconf LONG_BIT
>> This has nothing to do with how Dart VM was compiled

Please, run this script and post here results.

```
import "dart:io";
import "package:system_info/system_info.dart";

void main() {
  print("SysInfo.userSpaceBitness: ${SysInfo.userSpaceBitness}");
  print("Platform.version: ${Platform.version}");
}
```

>> Setting project.bits doesn't solve the problem because then everyone would have to change it specifically for their platform.

I cannot understand your problem.
Please explain it in detail (what you want and why you cannot that).

**Comment by mezoni** [comment]
>> SysInfo.userSpaceBitness returns 64 on my platform and it comes from running:
>> $ getconf LONG_BIT

getconf **LONG_BIT**
Number of bits in a type long int

**LP64/I32LP64**
Most Unix and Unix-like systems, e.g. Solaris, Linux, BSD, and OS X; z/OS
`Long is 64 bit`

**ILP32**
Most of today's 32-bit UNIX platforms use the ILP32 data model.
`Long is 32 bit`

Through the `getconf LONG_BIT` possible get the size of C long type only for the current running process (not for the kernel data model).

That is, it fully fit for their purpose (user space bitness).
If Dart VM compiled for 32-bit then it will run in 32-bit user space.

P.S.
May be you ask about the detection of the bitness of executable file on disk (PE, ELF)?

**Comment by mezoni** [comment]
>> Setting project.bits doesn't solve the problem because then everyone would have to change it specifically for their platform.

This depends on that what you want to achieve:
1. Use `ccompile` based library as the universal self-configurable tool which is able to compile the native extension for the current running Dart VM
2. Use `ccompile` only on your local (virtual) machines for pre-compilig the bunch of the dynamic libaries of the native extension for different platforms (for ditributing them in a single package with pre-compiled binaries).

What kind of task you wish solve (1 or 2)?

**Comment by mezoni** [comment]
Changelog
0.0.16
Fixed bug in detection of user space bitness on Mac OS X
