### ISSUE TITLE
How to run on iOS?

### ISSUE THREAD

**Issue by alxmoroz** [mezoni/system_info#5]
There is "iOS" label in Pub.dev, but I cannot run this package on iOS

**Comment by mezoni** [comment]
Hello, Alexandr!

>> There is "iOS" label in Pub.dev

If you think that I personally created this label, then you are mistaken.  
Ask the pub.dev developers about it.

>> but I cannot run this package on iOS

Everything is correct. Because Apple cares about you and does not allow the development of such software.

**Comment by alxmoroz** [comment]
ok, thanks for explanation! 
nice code, anyway!
good luck!

**Comment by mezoni** [comment]
@alxmoroz 
Thank you!
